clear;
clc;
fs = 360;
t = 0:1/fs:0.2;
N = length(t);
f = 20;
sinal = 2*sin(2*pi*f*t);
subplot(2, 2, 1);
plot(t, sinal);
title('Sinal Senoidal de 20Hz');
xlabel('Tempo [s]'); ylabel('Amplitude [V]');
f_noise = 60;
ruido = 2*sin(2*pi*f_noise*t);
subplot(2, 2, 2);
plot(t, ruido);
title('Sinal Senoidal de Ruido de 60Hz');
xlabel('Tempo [s]'); ylabel('Amplitude [V]');
sinal_ruidoso = sinal + ruido;
subplot(2, 2, 3);
plot(t, sinal_ruidoso); title('Sinal Ruidoso - Hz');
xlabel('Tempo [s]'); ylabel('Amplitude [V]');
y = fft(sinal_ruidoso);
y = y(1:floor(length(y)/2));
fr = (0:N-1)*fs/N;
fr = fr(1:floor(length(fr)/2));
subplot(2, 2, 4);
plot(fr, abs(y));
title('Espectro do Sinal Ruidoso');
xlabel('Frequencia [Hz]'); ylabel('y(f)');
